server:
  port: 8080
#  address: 127.0.0.1
  address: 0.0.0.0
spring:
#  profiles.active: "local"
  config:
    import: "optional:classpath:application-secret.yml"
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    dialect: org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: xldpa123
    sql-script-encoding: "UTF-8"

