server:
  port: 8080
#  address: 127.0.0.1
  address: 0.0.0.0
spring:
  profiles.active: "local"
  config:
    import: "optional:classpath:application-secret.yml"

  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    dialect: org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/sys
#    username: root
    url: jdbc:mariadb://koti-springboot2-webservice.csampsip3gfh.ap-northeast-2.rds.amazonaws.com:3306/formmail
    password: ${DB_PW}
    username: ${DB_NAME}
    sql-script-encoding: "UTF-8"
  jpa:
    properties:
      hibernate:
        "[format_sql]": true # 정렬된 SQL 출력
        "[auto_quote_keyword]": true
        show-sql: true # 사용되는 SQL 콘솔창에 출력
    hibernate:
      ddl-auto: none # 객체에 매핑되는 기존 테이블 자동 드랍 및 새로운 테이블 생성, create, none, create-drop
      defer-datasource-initialization: true
      mybatis:
        type-aliases-package: com.example.smsSpringTest.model.*
        configuration:
          map-underscore-to-camel-case: true
          default-executor-type: reuse
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.example.smsSpringTest.model.*
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: api-echo-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
sms:
  userId: ${SMS_ID}
  secureKey: ${SMS_SECURE}

holiday:
  service-key: ${HOLIDAY_KEY}

jwt:
  secret: ${JWT_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: https://koti-job.kro.kr/v1/jobsite/user/login/kakao
#  redirect-uri: http://localhost:8080/v1/jobsite/user/login/kakao

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: https://koti-job.kro.kr/v1/jobsite/user/login/naver
#  redirect-uri: http://localhost:8080/v1/jobsite/user/login/naver

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: https://koti-job.kro.kr/v1/jobsite/user/login/google
#  redirect-uri: http://localhost:8080/v1/jobsite/user/login/google

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error