server:
  port: 8080
#  address: 127.0.0.1
  address: 0.0.0.0
spring:
  profiles.active: "local"
  config:
    import: "optional:classpath:application-secret.yml"

    #-------
#    activeate.on-profile: jdbc
    #-------
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    dialect: org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/sys
#    username: root
#    password: xldpa123
    url: jdbc:mariadb://koti-springboot2-webservice.csampsip3gfh.ap-northeast-2.rds.amazonaws.com:3306/formmail
    password: xldpa123
    username: koreatm
    sql-script-encoding: "UTF-8"
  jpa:
    properties:
      hibernate:
        "[format_sql]": true # 정렬된 SQL 출력
        "[auto_quote_keyword]": true
        show-sql: true # 사용되는 SQL 콘솔창에 출력
    hibernate:
      ddl-auto: none # 객체에 매핑되는 기존 테이블 자동 드랍 및 새로운 테이블 생성, create, none, create-drop
      defer-datasource-initialization: true
      mybatis:
        type-aliases-package: com.example.smsSpringTest.model.*
        configuration:
          map-underscore-to-camel-case: true
          default-executor-type: reuse
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.example.smsSpringTest.model.*
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: api-echo-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
sms:
  userId: jobkoreatmsms
  secureKey: 31b3614fae273455f0bedf88862ec865

holiday:
  service-key: =pET%2F3OCUU7M9xFiirXa9PPBbmmT7mz0Dx7cgU8%2BUoziSye4j2xRC7cNFqgKAe7%2FPEYD%2F4m8WOgiBmUAPe%2FXetQ%3D%3D
